<?php

declare(strict_types=1);

namespace App\Domain\Identity;

/**
 * Identity of a user. Generated by the repository (see UserRepository::nextIdentity()).
 */
final readonly class UserId implements \Stringable
{
    private function __construct(public string $value)
    {
    }

    public static function fromString(string $value): self
    {
        if (trim($value) === '') {
            throw new \InvalidArgumentException('A user id cannot be empty.');
        }

        return new self($value);
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
