<?php

declare(strict_types=1);

namespace App\Domain\Shared;

/**
 * Base class for aggregate identities. Values are generated by repositories
 * (nextIdentity()), so the domain stays agnostic of the storage id format.
 */
abstract readonly class AggregateId implements \Stringable
{
    final protected function __construct(public string $value)
    {
    }

    public static function fromString(string $value): static
    {
        if (trim($value) === '') {
            throw new \InvalidArgumentException(sprintf('%s cannot be empty.', static::class));
        }

        return new static($value);
    }

    public function equals(self $other): bool
    {
        return $other instanceof static && $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
